In [3]:
# List of groceries
groceries = ["Bread", "Cookies", "Sweets", "Biscuits", "Honey"]
# Print the third item in groceries
print(groceries[2])

Sweets


In [4]:
# Name
my_full_name = "AMPEIRE EDGAR"
# Print 5th character
print(my_full_name[4])

I


In [5]:
# Loop through the grocery items and print each item
for item in groceries:
    print(item)

Bread
Cookies
Sweets
Biscuits
Honey


In [6]:
# Print sqaures of numbers from 0 to 10
for integer in range(0, 11):
    print(integer ** 2)

0
1
4
9
16
25
36
49
64
81
100


In [10]:
import datetime as dt

# Time variable
my_time = dt.time(hour=5, minute=25)

# print the time
print(my_time)

05:25:00


In [12]:
import numpy as np

#  Create a 2 * 2 array with 1s on the diagonal
my_array = np.diag([1,1])


# Print the array
print(my_array)

[[1 0]
 [0 1]]


In [13]:
# Create an array with ones on every element
ones_array = np.ones([2, 3, 2])

print(ones_array)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [22]:
# Create 3 * 3 array
my_3_by_3_array = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

# Print the element from the intersection of the 2nd row and 3rd column
print(my_3_by_3_array[1, 2])

6


In [23]:
# Print the shape of "my3by3Array"
print(my_3_by_3_array.shape)

(3, 3)


In [31]:
# Iterate through the rows and columns of my3by3Array
for i in my_3_by_3_array:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9


In [35]:
#  Square every number in the array and print the maximum value contained in it
squares = my_3_by_3_array ** 2

#  Get the maximum value
max_value = np.amax(squares)

# Print the maximum
print(max_value)

81
